source "https://rubygems.org"

ruby "~> 3.3"

gem "dtext", git: "https://github.com/e621ng/dtext.git", tag: "2.0.3", require: "dtext"

gem "sinatra", "~> 4.1"
gem "rackup", "~> 2.2"
gem "puma", "~> 6.5"
gem "json", "~> 2.7"
